'backend: genten':
  - '/\bgenten\b/i'
  - '/\blinux\b/i'
  - '(pacman|deb|appimage)'
  - '/\bmac\b/i'

'platform: linux':
  - '/\blinux\b/i'
  - '(pacman|deb|appimage|rpm)'

'platform: macos':
  - '/\bmac\b/i'
  - '(dmg)'

'backend: dotnet':
  - '/\bwindows\b/i'
  - '/\bmicrosoft\b/i'

'feat: lastfm':
  - '/\blastfm\b/i'

'feat: discordrpc':
  - '/\bdiscordrpc\b/i'

'iz: websocket':
  - '/\bsocket\b/i'
  - '/\bws\b/i'

'feat: lyrics':
  - '/\blyric\b/i'
