'feat: lastfm':
  - '/\blastfm\b/i'

'feat: discordrpc':
  - '/\bdiscordrpc\b/i'

'iz: websocket':
  - '/\bsocket\b/i'
  - '/\bws\b/i'

'feat: lyrics':
  - '/\blyric\b/i'

'feat: audiolab':
  - '/\baudiolab\b/i'
  - '/\beq\b/i'
  - '/\bcap\b/i'

'app: playback':
  - '/\bplay\b/i'