name: Bug Report
description: If you encounter an issue whilst using our app, please use this template to help improve the app.
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Before you start, if you have a feature request please forward it to our [Discord server](https://discord.com/invite/AppleMusic), where it can be discussed within the community.
        *Opening Feature Requests on GitHub will be closed and ignored. You have been warned!*
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
          required: true
        - label: I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
          required: true
        - label: I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
          required: true
  - type: dropdown
    attributes:
      label: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: build_details
    attributes:
      label: Build Details
      description: When did you install Cider? You can find your build details from [this guide](https://github.com/ciderapp/Cider-2/blob/main/docs/FINDING_VERSION.md).
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System Version
      description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
      placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug you encountered. Tell us what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug, tell us how you did it so we can do it ourselves.
      placeholder: 1. Clicked on...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    id: uid
    attributes:
      label: Connect Device ID
      description: Helps us determine what version you are using (optional)
    validations:
      required: false
  - type: input
    id: ver
    attributes:
      label: Build timestamp
      description: If this is not filled out already, feel free to ignore (optional)
    validations:
      required: false
