name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 5 * * *'

permissions:
  issues: write
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: gen
        with:
          app-id: '363587'
          private-key: ${{ secrets.APP_KEY }}
          
      - uses: actions/stale@v9
        with:
          repo-token: ${{ steps.gen.outputs.access-token }}
          stale-issue-label: 'stale'
          stale-issue-message: |
            **Hello again!**  

            We've noticed that you haven't replied in a while. Unfortunately, our team isn't always able to address issues as quickly as we'd like. To help us assist you more efficiently, please provide the following information:  

            1. Ensure your client is as up-to-date as possible. You can do this by using the experimental release on Taproom (if available) and the PTB release through the in-app updater.  
            2. Let us know if the issue is still present. If it is, please provide the version you're using and mention any changes you've noticed since reporting the issue.  

            This information will help us identify whether the issue has already been resolved.  

            Please try to update us within the next 20 days; otherwise, we will close this issue.  

            Thanks for your help! :smiley:


          close-issue-message: |
            **Hello!**  

            We have closed this issue due to inactivity. If you are still experiencing this bug in a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md#supported-versions), please open a new issue with the necessary information.  
            
            Thank you for your understanding! 👋          
          days-before-issue-stale: 10
          days-before-issue-close: 20
          exempt-issue-labels: "confirmed,keep-open,security,accessibility/scaling"
          exempt-all-assignees: true
          exempt-all-issue-milestones: true
