on:
  issues:
    types: [opened]

permissions:
  issues: read

jobs:
  first-interaction:
    name: First Interaction
    runs-on: ubuntu-latest
    steps:
      - uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: gen
        with:
          app-id: '363587'
          private-key: ${{ secrets.APP_KEY }}
          
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ steps.gen.outputs.access-token }}
          issue-message: |-
            Hello @${{github.actor}} :wave:

            We really appreciate you taking the time to report this issue, please double check your issue to make sure you are clear and concise in your description. This will help us to help you as quickly as possible.

            We'd like to ask you be patient and we will get back to you as soon as we can.

            In the meantime, take a look at our [FAQs](https://github.com/ciderapp/Cider-2/tree/main?tab=readme-ov-file#faq) which may answer your question.

            Thanks again and we hope you enjoy the app! :smiley:

  label-component:
    name: Automatically Label Issue
    runs-on: ubuntu-latest
    steps:
      - uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: gen
        with:
          app-id: '363587'
          private-key: ${{ secrets.APP_KEY }}

      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ steps.gen.outputs.access-token }}
          sparse-checkout: |
            .github

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug.yaml

      - name: Set the Labels
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          token: ${{ steps.gen.outputs.access-token }}

  add-to-project:
    name: Add Issue to Project
    runs-on: ubuntu-latest
    steps:
      - uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: gen
        with:
          app-id: '363587'
          private-key: ${{ secrets.APP_KEY }}
          
      - run: gh issue edit "$NUMBER" --add-project "Cider - Bug Reports"
        env:
          GH_TOKEN: ${{ steps.gen.outputs.access-token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
