on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |-
            Hello @${{github.actor}} :wave:

            We really appreciate you taking the time to report this issue, please double check your issue to make sure you are clear and concise in your description. This will help us to help you as quickly as possible.

            We'd like to ask you be patient and we will get back to you as soon as we can.

            In the meantime, take a look at our [FAQs](https://github.com/ciderapp/Cider-2/tree/main?tab=readme-ov-file#faq) which may answer your question.

            Thanks again and we hope you enjoy the app! :smiley:

  auto-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          sync-labels: 1
          include-title: 1
